# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-12 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifier", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="nick_name",
            new_name="account",
        ),
        migrations.AddField(
            model_name="contact",
            name="sender",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contact",
            name="token",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
