# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(choices=[('EQ', 'Is equal'), ('NE', 'Not equal'), ('IN', 'Contains'), ('NI', 'Not contain')], max_length=3)),
                ('assertion', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Project')),
            ],
        ),
    ]
