# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_frontendtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendtest',
            name='url',
            field=models.URLField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
