# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-09 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_auto_20170409_1335"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="backup_active",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
