# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-09 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_project_backup_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="class_type",
            field=models.CharField(
                choices=[("BACK", "Backup"), ("TEST", "Testing")],
                default="TEST",
                max_length=4,
            ),
            preserve_default=False,
        ),
    ]
