# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_auto_20170615_2346"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lotrekuser",
            name="twilio_account",
        ),
        migrations.RemoveField(
            model_name="lotrekuser",
            name="twilio_token",
        ),
    ]
