# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-19 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_auto_20170615_2347"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="domain",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
