# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-27 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20170724_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='project',
            name='managed',
        ),
    ]
