# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-27 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180127_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
