# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-27 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180127_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
