# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20180127_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='panelonline',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='panelonline_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='panelonline_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
