# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-09-28 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_auto_20180127_1941"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
