# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20180302_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='panelonline',
            new_name='panel_online',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='panelonline_password',
            new_name='panel_online_password',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='panelonline_username',
            new_name='panel_online_username',
        ),
    ]
