# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20180302_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='panel_online',
            new_name='online_panel',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='panel_online_password',
            new_name='online_panel_password',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='panel_online_username',
            new_name='online_panel_username',
        ),
    ]
