# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20180302_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='reseller_panel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='reseller_panel_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='reseller_panel_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
