# Generated by Django 2.2.5 on 2019-12-06 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_auto_20191019_1806"),
        ("main", "0021_auto_20191206_1136"),
    ]

    operations = []
