# Generated by Django 2.2.5 on 2019-12-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_merge_20191206_1138"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=200)),
                ("end_time", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
