# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20180302_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='name_on_reseller',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
