# Generated by Django 2.2.5 on 2019-12-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
