# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_domain_registar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='registar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Registar'),
        ),
    ]
