# Generated by Django 2.2.5 on 2019-12-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_domain_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='domains',
            field=models.ManyToManyField(to='main.Domain'),
        ),
    ]
