# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20180302_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='panel_registar',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='password_panel_registar',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='username_panel_registar',
        ),
        migrations.AddField(
            model_name='registar',
            name='panel_registar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registar',
            name='password_panel_registar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registar',
            name='username_panel_registar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
