# Generated by Django 2.2.5 on 2019-12-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_machine_domains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='domains',
        ),
        migrations.AddField(
            model_name='domain',
            name='site',
            field=models.ManyToManyField(to='main.Machine'),
        ),
    ]
