# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20180302_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
