# Generated by Django 2.2.5 on 2019-12-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_auto_20191206_1555"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="server_mail",
            field=models.ManyToManyField(to="main.Machine"),
        ),
        migrations.AlterField(
            model_name="domain",
            name="site",
            field=models.ManyToManyField(related_name="site", to="main.Machine"),
        ),
    ]
