# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20180306_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
