# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20180307_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainregistrant',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
