# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20180307_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='torenew',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
