# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_domain_torenew'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='torenew',
            new_name='to_renew',
        ),
    ]
