# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20180307_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='management_contract',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
