# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_machine_management_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
