# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20180307_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='certificates',
            field=models.ManyToManyField(blank=True, null=True, to='main.Certificate'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='domains',
            field=models.ManyToManyField(blank=True, null=True, to='main.Domain'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='machines',
            field=models.ManyToManyField(blank=True, null=True, to='main.Machine'),
        ),
    ]
