# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_payment_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
