# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_payment_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='month',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
    ]
