# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_payment_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='registrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Domainregistrant'),
        ),
    ]
