# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_certificate_registrant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='registrant',
            new_name='customer',
        ),
    ]
