# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20180313_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='calendar_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
