# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_domain_calendar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='calendar_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
