# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-17 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_certificate_calendar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='calendar_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
